variable "project_id" {}
variable "region" {}
variable "cluster_name" {}
variable "machine_type" {}
variable "node_locations" {}
variable "network" {}
variable "subnetwork" {}
variable "public_pool_name" {}
variable "public_node_count" {}
variable "min_public_node_count" {}
variable "max_public_node_count" {}
variable "private_pool_name" {}
variable "private_node_count" {}
variable "min_private_node_count" {}
variable "max_private_node_count" {}
